title: "Silicon Soundscapes"
description: A journey through creating Tullia, an FM synthesiser on an FPGA
theme: just-the-docs

url: https://ydigikat.github.io
#baseurl: /silicon-soundscapes

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

color_scheme: nil

nav_sort: case_sensitive # Capital letters sorted before lowercase

mermaid:
  version: "9.1.6"

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "©2021 YDigikat"

callouts_level: quiet
callouts:
  highlight: 
    color: yellow
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green
  note:
    title: Note
    color: purple

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

